# Generated by Django 4.0.3 on 2022-04-01 13:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='service_region',
            field=models.CharField(choices=[('south', 'JHB South'), ('north', 'JHB North'), ('west', 'JHB West'), ('east', 'JHB East')], default='south', max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='date_listed',
            field=models.DateField(default=datetime.datetime.now, max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime.now, max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('computers', 'Computers'), ('arts_and_crafts', 'Arts & Crafts'), ('automotive', 'Automotive'), ('womens_fasion', 'Womens fasion'), ('mens_fasion', 'Mens fasion'), ('health', 'Health'), ('movies_and_games', 'Movies & Games'), ('software', 'Software'), ('sports', 'Sports'), ('books', 'Books'), ('general', 'General')], default='general', max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10.5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='item_name', max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='description', max_length=1000),
        ),
        migrations.DeleteModel(
            name='CatalogueOwner',
        ),
    ]
