# Generated by Django 4.0.3 on 2022-04-01 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalogue_service_region_product_date_listed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='service_region',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.FloatField(default=1.1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
