# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: SSH login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}

      - name: change
        run: cd ../
        
      - name: change dir
        run: |
          ll
          cd home/cole/
        
      - name: clone
        run: git clone https://github.com/Cole694/api-django
        
      - name: change dir
        run: cd api-django/
        
      - name: make venv
        run: python3 -m venv env
            
      - name: activate venv
        run: source env/bin/activate
            
      - name: docker compose
        run: docker-compose up -d
            
      - name: bash into
        run: docker exec -it api-django_web_1 bash
            
      - name: migrate
        run: |
          python manage.py migrate
          exit
                
      
            
              
          
